package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineAbbrevId generated by hbm2java
 */
public class BaselineAbbrevId implements java.io.Serializable {

	private String kontext;
	private String short_;

	public BaselineAbbrevId() {
	}

	public BaselineAbbrevId(String kontext, String short_) {
		this.kontext = kontext;
		this.short_ = short_;
	}

	public String getKontext() {
		return this.kontext;
	}

	public void setKontext(String kontext) {
		this.kontext = kontext;
	}

	public String getShort_() {
		return this.short_;
	}

	public void setShort_(String short_) {
		this.short_ = short_;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BaselineAbbrevId))
			return false;
		BaselineAbbrevId castOther = (BaselineAbbrevId) other;

		return ((this.getKontext() == castOther.getKontext()) || (this
				.getKontext() != null
				&& castOther.getKontext() != null && this.getKontext().equals(
				castOther.getKontext())))
				&& ((this.getShort_() == castOther.getShort_()) || (this
						.getShort_() != null
						&& castOther.getShort_() != null && this.getShort_()
						.equals(castOther.getShort_())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKontext() == null ? 0 : this.getKontext().hashCode());
		result = 37 * result
				+ (getShort_() == null ? 0 : this.getShort_().hashCode());
		return result;
	}

}
