package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineAbbrev generated by hbm2java
 */
public class BaselineAbbrev implements java.io.Serializable {

	private BaselineAbbrevId id;
	private String version;
	private String longt;

	public BaselineAbbrev() {
	}

	public BaselineAbbrev(BaselineAbbrevId id) {
		this.id = id;
	}

	public BaselineAbbrev(BaselineAbbrevId id, String longt) {
		this.id = id;
		this.longt = longt;
	}

	public BaselineAbbrevId getId() {
		return this.id;
	}

	public void setId(BaselineAbbrevId id) {
		this.id = id;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getLongt() {
		return this.longt;
	}

	public void setLongt(String longt) {
		this.longt = longt;
	}

}
