package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineMsgusrgrId generated by hbm2java
 */
public class BaselineMsgusrgrId implements java.io.Serializable {

	private Double key;
	private String usergroup;

	public BaselineMsgusrgrId() {
	}

	public BaselineMsgusrgrId(Double key, String usergroup) {
		this.key = key;
		this.usergroup = usergroup;
	}

	public Double getKey() {
		return this.key;
	}

	public void setKey(Double key) {
		this.key = key;
	}

	public String getUsergroup() {
		return this.usergroup;
	}

	public void setUsergroup(String usergroup) {
		this.usergroup = usergroup;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BaselineMsgusrgrId))
			return false;
		BaselineMsgusrgrId castOther = (BaselineMsgusrgrId) other;

		return ((this.getKey() == castOther.getKey()) || (this.getKey() != null
				&& castOther.getKey() != null && this.getKey().equals(
				castOther.getKey())))
				&& ((this.getUsergroup() == castOther.getUsergroup()) || (this
						.getUsergroup() != null
						&& castOther.getUsergroup() != null && this
						.getUsergroup().equals(castOther.getUsergroup())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKey() == null ? 0 : this.getKey().hashCode());
		result = 37 * result
				+ (getUsergroup() == null ? 0 : this.getUsergroup().hashCode());
		return result;
	}

}
