package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineDefPrintTmpId generated by hbm2java
 */
public class BaselineDefPrintTmpId implements java.io.Serializable {

	private Double reportNo;
	private String reportType;
	private Double key;
	private Double fudKey;

	public BaselineDefPrintTmpId() {
	}

	public BaselineDefPrintTmpId(Double reportNo, String reportType,
			Double key, Double fudKey) {
		this.reportNo = reportNo;
		this.reportType = reportType;
		this.key = key;
		this.fudKey = fudKey;
	}

	public Double getReportNo() {
		return this.reportNo;
	}

	public void setReportNo(Double reportNo) {
		this.reportNo = reportNo;
	}

	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	public Double getKey() {
		return this.key;
	}

	public void setKey(Double key) {
		this.key = key;
	}

	public Double getFudKey() {
		return this.fudKey;
	}

	public void setFudKey(Double fudKey) {
		this.fudKey = fudKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BaselineDefPrintTmpId))
			return false;
		BaselineDefPrintTmpId castOther = (BaselineDefPrintTmpId) other;

		return ((this.getReportNo() == castOther.getReportNo()) || (this
				.getReportNo() != null
				&& castOther.getReportNo() != null && this.getReportNo()
				.equals(castOther.getReportNo())))
				&& ((this.getReportType() == castOther.getReportType()) || (this
						.getReportType() != null
						&& castOther.getReportType() != null && this
						.getReportType().equals(castOther.getReportType())))
				&& ((this.getKey() == castOther.getKey()) || (this.getKey() != null
						&& castOther.getKey() != null && this.getKey().equals(
						castOther.getKey())))
				&& ((this.getFudKey() == castOther.getFudKey()) || (this
						.getFudKey() != null
						&& castOther.getFudKey() != null && this.getFudKey()
						.equals(castOther.getFudKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getReportNo() == null ? 0 : this.getReportNo().hashCode());
		result = 37
				* result
				+ (getReportType() == null ? 0 : this.getReportType()
						.hashCode());
		result = 37 * result
				+ (getKey() == null ? 0 : this.getKey().hashCode());
		result = 37 * result
				+ (getFudKey() == null ? 0 : this.getFudKey().hashCode());
		return result;
	}

}
