package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineSecClass generated by hbm2java
 */
public class BaselineSecClass implements java.io.Serializable {

	private String shortname;
	private String priority;
	private String longname;

	public BaselineSecClass() {
	}

	public BaselineSecClass(String shortname) {
		this.shortname = shortname;
	}

	public BaselineSecClass(String shortname, String priority, String longname) {
		this.shortname = shortname;
		this.priority = priority;
		this.longname = longname;
	}

	public String getShortname() {
		return this.shortname;
	}

	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	public String getLongname() {
		return this.longname;
	}

	public void setLongname(String longname) {
		this.longname = longname;
	}

}
