package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineMsgFunc generated by hbm2java
 */
public class BaselineMsgFunc implements java.io.Serializable {

	private BaselineMsgFuncId id;
	private String io;

	public BaselineMsgFunc() {
	}

	public BaselineMsgFunc(BaselineMsgFuncId id) {
		this.id = id;
	}

	public BaselineMsgFunc(BaselineMsgFuncId id, String io) {
		this.id = id;
		this.io = io;
	}

	public BaselineMsgFuncId getId() {
		return this.id;
	}

	public void setId(BaselineMsgFuncId id) {
		this.id = id;
	}

	public String getIo() {
		return this.io;
	}

	public void setIo(String io) {
		this.io = io;
	}

}
