package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineDifudrefId generated by hbm2java
 */
public class BaselineDifudrefId implements java.io.Serializable {

	private double di;
	private double fudn;

	public BaselineDifudrefId() {
	}

	public BaselineDifudrefId(double di, double fudn) {
		this.di = di;
		this.fudn = fudn;
	}

	public double getDi() {
		return this.di;
	}

	public void setDi(double di) {
		this.di = di;
	}

	public double getFudn() {
		return this.fudn;
	}

	public void setFudn(double fudn) {
		this.fudn = fudn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BaselineDifudrefId))
			return false;
		BaselineDifudrefId castOther = (BaselineDifudrefId) other;

		return (this.getDi() == castOther.getDi())
				&& (this.getFudn() == castOther.getFudn());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getDi();
		result = 37 * result + (int) this.getFudn();
		return result;
	}

}
