package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineDefPrintTmp generated by hbm2java
 */
public class BaselineDefPrintTmp implements java.io.Serializable {

	private BaselineDefPrintTmpId id;

	public BaselineDefPrintTmp() {
	}

	public BaselineDefPrintTmp(BaselineDefPrintTmpId id) {
		this.id = id;
	}

	public BaselineDefPrintTmpId getId() {
		return this.id;
	}

	public void setId(BaselineDefPrintTmpId id) {
		this.id = id;
	}

}
