package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineAccessright generated by hbm2java
 */
public class BaselineAccessright implements java.io.Serializable {

	private double key;
	private String username;
	private Double class_;
	private String right;

	public BaselineAccessright() {
	}

	public BaselineAccessright(double key) {
		this.key = key;
	}

	public BaselineAccessright(double key, String username, Double class_,
			String right) {
		this.key = key;
		this.username = username;
		this.class_ = class_;
		this.right = right;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Double getClass_() {
		return this.class_;
	}

	public void setClass_(Double class_) {
		this.class_ = class_;
	}

	public String getRight() {
		return this.right;
	}

	public void setRight(String right) {
		this.right = right;
	}

}
