package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineSetnlcmnt generated by hbm2java
 */
public class BaselineSetnlcmnt implements java.io.Serializable {

	private BaselineSetnlcmntId id;

	public BaselineSetnlcmnt() {
	}

	public BaselineSetnlcmnt(BaselineSetnlcmntId id) {
		this.id = id;
	}

	public BaselineSetnlcmntId getId() {
		return this.id;
	}

	public void setId(BaselineSetnlcmntId id) {
		this.id = id;
	}

}
