package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineClformbas generated by hbm2java
 */
public class BaselineClformbas implements java.io.Serializable {

	private double key;
	private String classname;
	private Date revdate;
	private String linelength;
	private String flddescmk;
	private String eosmarker;
	private String fldmarker;
	private String nodatamk;
	private String efldmin;
	private String efldmax;
	private String cfldmin;
	private String cfldmax;
	private String addset;
	private String addseg;
	private String addmsg;
	private String srcFileName;
	private String classdesc;
	private String classtype;
	private String priority;
	private Date auditdate;
	private Double maxmsgname;
	private Double maxsetidlen;
	private Double maxfudn;
	private String setcontmk;
	private String textcontmk;
	private String maxnumlines;

	public BaselineClformbas() {
	}

	public BaselineClformbas(double key) {
		this.key = key;
	}

	public BaselineClformbas(double key, String classname, Date revdate,
			String linelength, String flddescmk, String eosmarker,
			String fldmarker, String nodatamk, String efldmin, String efldmax,
			String cfldmin, String cfldmax, String addset, String addseg,
			String addmsg, String srcFileName, String classdesc,
			String classtype, String priority, Date auditdate,
			Double maxmsgname, Double maxsetidlen, Double maxfudn,
			String setcontmk, String textcontmk, String maxnumlines) {
		this.key = key;
		this.classname = classname;
		this.revdate = revdate;
		this.linelength = linelength;
		this.flddescmk = flddescmk;
		this.eosmarker = eosmarker;
		this.fldmarker = fldmarker;
		this.nodatamk = nodatamk;
		this.efldmin = efldmin;
		this.efldmax = efldmax;
		this.cfldmin = cfldmin;
		this.cfldmax = cfldmax;
		this.addset = addset;
		this.addseg = addseg;
		this.addmsg = addmsg;
		this.srcFileName = srcFileName;
		this.classdesc = classdesc;
		this.classtype = classtype;
		this.priority = priority;
		this.auditdate = auditdate;
		this.maxmsgname = maxmsgname;
		this.maxsetidlen = maxsetidlen;
		this.maxfudn = maxfudn;
		this.setcontmk = setcontmk;
		this.textcontmk = textcontmk;
		this.maxnumlines = maxnumlines;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	public Date getRevdate() {
		return this.revdate;
	}

	public void setRevdate(Date revdate) {
		this.revdate = revdate;
	}

	public String getLinelength() {
		return this.linelength;
	}

	public void setLinelength(String linelength) {
		this.linelength = linelength;
	}

	public String getFlddescmk() {
		return this.flddescmk;
	}

	public void setFlddescmk(String flddescmk) {
		this.flddescmk = flddescmk;
	}

	public String getEosmarker() {
		return this.eosmarker;
	}

	public void setEosmarker(String eosmarker) {
		this.eosmarker = eosmarker;
	}

	public String getFldmarker() {
		return this.fldmarker;
	}

	public void setFldmarker(String fldmarker) {
		this.fldmarker = fldmarker;
	}

	public String getNodatamk() {
		return this.nodatamk;
	}

	public void setNodatamk(String nodatamk) {
		this.nodatamk = nodatamk;
	}

	public String getEfldmin() {
		return this.efldmin;
	}

	public void setEfldmin(String efldmin) {
		this.efldmin = efldmin;
	}

	public String getEfldmax() {
		return this.efldmax;
	}

	public void setEfldmax(String efldmax) {
		this.efldmax = efldmax;
	}

	public String getCfldmin() {
		return this.cfldmin;
	}

	public void setCfldmin(String cfldmin) {
		this.cfldmin = cfldmin;
	}

	public String getCfldmax() {
		return this.cfldmax;
	}

	public void setCfldmax(String cfldmax) {
		this.cfldmax = cfldmax;
	}

	public String getAddset() {
		return this.addset;
	}

	public void setAddset(String addset) {
		this.addset = addset;
	}

	public String getAddseg() {
		return this.addseg;
	}

	public void setAddseg(String addseg) {
		this.addseg = addseg;
	}

	public String getAddmsg() {
		return this.addmsg;
	}

	public void setAddmsg(String addmsg) {
		this.addmsg = addmsg;
	}

	public String getSrcFileName() {
		return this.srcFileName;
	}

	public void setSrcFileName(String srcFileName) {
		this.srcFileName = srcFileName;
	}

	public String getClassdesc() {
		return this.classdesc;
	}

	public void setClassdesc(String classdesc) {
		this.classdesc = classdesc;
	}

	public String getClasstype() {
		return this.classtype;
	}

	public void setClasstype(String classtype) {
		this.classtype = classtype;
	}

	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

	public Double getMaxmsgname() {
		return this.maxmsgname;
	}

	public void setMaxmsgname(Double maxmsgname) {
		this.maxmsgname = maxmsgname;
	}

	public Double getMaxsetidlen() {
		return this.maxsetidlen;
	}

	public void setMaxsetidlen(Double maxsetidlen) {
		this.maxsetidlen = maxsetidlen;
	}

	public Double getMaxfudn() {
		return this.maxfudn;
	}

	public void setMaxfudn(Double maxfudn) {
		this.maxfudn = maxfudn;
	}

	public String getSetcontmk() {
		return this.setcontmk;
	}

	public void setSetcontmk(String setcontmk) {
		this.setcontmk = setcontmk;
	}

	public String getTextcontmk() {
		return this.textcontmk;
	}

	public void setTextcontmk(String textcontmk) {
		this.textcontmk = textcontmk;
	}

	public String getMaxnumlines() {
		return this.maxnumlines;
	}

	public void setMaxnumlines(String maxnumlines) {
		this.maxnumlines = maxnumlines;
	}

}
