package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineMsgusrgr generated by hbm2java
 */
public class BaselineMsgusrgr implements java.io.Serializable {

	private BaselineMsgusrgrId id;

	public BaselineMsgusrgr() {
	}

	public BaselineMsgusrgr(BaselineMsgusrgrId id) {
		this.id = id;
	}

	public BaselineMsgusrgrId getId() {
		return this.id;
	}

	public void setId(BaselineMsgusrgrId id) {
		this.id = id;
	}

}
