package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineDifudref generated by hbm2java
 */
public class BaselineDifudref implements java.io.Serializable {

	private BaselineDifudrefId identifiant;
	private Date auditdate;

	public BaselineDifudref() {
	}

	public BaselineDifudref(BaselineDifudrefId id) {
		this.identifiant = id;
	}

	public BaselineDifudref(BaselineDifudrefId id, Date auditdate) {
		this.identifiant = id;
		this.auditdate = auditdate;
	}

	public BaselineDifudrefId getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(BaselineDifudrefId id) {
		this.identifiant = id;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

}
