package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineMsgdef generated by hbm2java
 */
public class BaselineMsgdef implements java.io.Serializable {

	private BaselineMsgdefId id;
	private String operator;
	private String fldvalue;

	public BaselineMsgdef() {
	}

	public BaselineMsgdef(BaselineMsgdefId id) {
		this.id = id;
	}

	public BaselineMsgdef(BaselineMsgdefId id, String operator, String fldvalue) {
		this.id = id;
		this.operator = operator;
		this.fldvalue = fldvalue;
	}

	public BaselineMsgdefId getId() {
		return this.id;
	}

	public void setId(BaselineMsgdefId id) {
		this.id = id;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getFldvalue() {
		return this.fldvalue;
	}

	public void setFldvalue(String fldvalue) {
		this.fldvalue = fldvalue;
	}

}
