package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineMsgnlcmnt generated by hbm2java
 */
public class BaselineMsgnlcmnt implements java.io.Serializable {

	private BaselineMsgnlcmntId id;

	public BaselineMsgnlcmnt() {
	}

	public BaselineMsgnlcmnt(BaselineMsgnlcmntId id) {
		this.id = id;
	}

	public BaselineMsgnlcmntId getId() {
		return this.id;
	}

	public void setId(BaselineMsgnlcmntId id) {
		this.id = id;
	}

}
