package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineGlobalFuncs generated by hbm2java
 */
public class BaselineGlobalFuncs implements java.io.Serializable {

	private double key;
	private String name;
	private String help;

	public BaselineGlobalFuncs() {
	}

	public BaselineGlobalFuncs(double key) {
		this.key = key;
	}

	public BaselineGlobalFuncs(double key, String name, String help) {
		this.key = key;
		this.name = name;
		this.help = help;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getHelp() {
		return this.help;
	}

	public void setHelp(String help) {
		this.help = help;
	}

}
