package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineClnlcmnt generated by hbm2java
 */
public class BaselineClnlcmnt implements java.io.Serializable {

	private BaselineClnlcmntId id;

	public BaselineClnlcmnt() {
	}

	public BaselineClnlcmnt(BaselineClnlcmntId id) {
		this.id = id;
	}

	public BaselineClnlcmntId getId() {
		return this.id;
	}

	public void setId(BaselineClnlcmntId id) {
		this.id = id;
	}

}
