package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineDibasic generated by hbm2java
 */
public class BaselineDibasic implements java.io.Serializable {

	private double key;
	private Double context;
	private String diname;
	private String dnclass;
	private String diexp;
	private String declass;
	private String dicharcode;
	private String dcclass;
	private Double diseqno;
	private String dihdrind;
	private Date auditdate;
	private Double diId;

	public BaselineDibasic() {
	}

	public BaselineDibasic(double key) {
		this.key = key;
	}

	public BaselineDibasic(double key, Double context, String diname,
			String dnclass, String diexp, String declass, String dicharcode,
			String dcclass, Double diseqno, String dihdrind, Date auditdate,
			Double diId) {
		this.key = key;
		this.context = context;
		this.diname = diname;
		this.dnclass = dnclass;
		this.diexp = diexp;
		this.declass = declass;
		this.dicharcode = dicharcode;
		this.dcclass = dcclass;
		this.diseqno = diseqno;
		this.dihdrind = dihdrind;
		this.auditdate = auditdate;
		this.diId = diId;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public Double getContext() {
		return this.context;
	}

	public void setContext(Double context) {
		this.context = context;
	}

	public String getDiname() {
		return this.diname;
	}

	public void setDiname(String diname) {
		this.diname = diname;
	}

	public String getDnclass() {
		return this.dnclass;
	}

	public void setDnclass(String dnclass) {
		this.dnclass = dnclass;
	}

	public String getDiexp() {
		return this.diexp;
	}

	public void setDiexp(String diexp) {
		this.diexp = diexp;
	}

	public String getDeclass() {
		return this.declass;
	}

	public void setDeclass(String declass) {
		this.declass = declass;
	}

	public String getDicharcode() {
		return this.dicharcode;
	}

	public void setDicharcode(String dicharcode) {
		this.dicharcode = dicharcode;
	}

	public String getDcclass() {
		return this.dcclass;
	}

	public void setDcclass(String dcclass) {
		this.dcclass = dcclass;
	}

	public Double getDiseqno() {
		return this.diseqno;
	}

	public void setDiseqno(Double diseqno) {
		this.diseqno = diseqno;
	}

	public String getDihdrind() {
		return this.dihdrind;
	}

	public void setDihdrind(String dihdrind) {
		this.dihdrind = dihdrind;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

	public Double getDiId() {
		return this.diId;
	}

	public void setDiId(Double diId) {
		this.diId = diId;
	}

}
