package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineClsetreplna generated by hbm2java
 */
public class BaselineClsetreplna implements java.io.Serializable {

	private BaselineClsetreplnaId id;

	public BaselineClsetreplna() {
	}

	public BaselineClsetreplna(BaselineClsetreplnaId id) {
		this.id = id;
	}

	public BaselineClsetreplnaId getId() {
		return this.id;
	}

	public void setId(BaselineClsetreplnaId id) {
		this.id = id;
	}

}
