package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineClsetreplnaId generated by hbm2java
 */
public class BaselineClsetreplnaId implements java.io.Serializable {

	private Double key;
	private String class_;
	private Date auditdate;
	private String setreplna;

	public BaselineClsetreplnaId() {
	}

	public BaselineClsetreplnaId(Double key, String class_, Date auditdate,
			String setreplna) {
		this.key = key;
		this.class_ = class_;
		this.auditdate = auditdate;
		this.setreplna = setreplna;
	}

	public Double getKey() {
		return this.key;
	}

	public void setKey(Double key) {
		this.key = key;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

	public String getSetreplna() {
		return this.setreplna;
	}

	public void setSetreplna(String setreplna) {
		this.setreplna = setreplna;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BaselineClsetreplnaId))
			return false;
		BaselineClsetreplnaId castOther = (BaselineClsetreplnaId) other;

		return ((this.getKey() == castOther.getKey()) || (this.getKey() != null
				&& castOther.getKey() != null && this.getKey().equals(
				castOther.getKey())))
				&& ((this.getClass_() == castOther.getClass_()) || (this
						.getClass_() != null
						&& castOther.getClass_() != null && this.getClass_()
						.equals(castOther.getClass_())))
				&& ((this.getAuditdate() == castOther.getAuditdate()) || (this
						.getAuditdate() != null
						&& castOther.getAuditdate() != null && this
						.getAuditdate().equals(castOther.getAuditdate())))
				&& ((this.getSetreplna() == castOther.getSetreplna()) || (this
						.getSetreplna() != null
						&& castOther.getSetreplna() != null && this
						.getSetreplna().equals(castOther.getSetreplna())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKey() == null ? 0 : this.getKey().hashCode());
		result = 37 * result
				+ (getClass_() == null ? 0 : this.getClass_().hashCode());
		result = 37 * result
				+ (getAuditdate() == null ? 0 : this.getAuditdate().hashCode());
		result = 37 * result
				+ (getSetreplna() == null ? 0 : this.getSetreplna().hashCode());
		return result;
	}

}
