package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineFudbasic generated by hbm2java
 */
public class BaselineFudbasic implements java.io.Serializable {

	private double key;
	private Double clcontext;
	private Double context;
	private String fudn;
	private String operuse;
	private String fudname;
	private String fudmin;
	private String fudmax;
	private String typchars;
	private String fudjustify;
	private String natostat;
	private Date nmoddate;
	private Date auditdate;
	private String clname;
	private String title;
	private String template;
	private String templateLength;
	private String dataType;
	private String mfslabel;
	private String freetextind;
	private String fudclass;
	private String fnclass;
	private String bitsize;
	private String sinc;
	private String qinc;
	private String offset;

	public BaselineFudbasic() {
	}

	public BaselineFudbasic(double key) {
		this.key = key;
	}

	public BaselineFudbasic(double key, Double clcontext, Double context,
			String fudn, String operuse, String fudname, String fudmin,
			String fudmax, String typchars, String fudjustify, String natostat,
			Date nmoddate, Date auditdate, String clname, String title,
			String template, String templateLength, String dataType,
			String mfslabel, String freetextind, String fudclass,
			String fnclass, String bitsize, String sinc, String qinc,
			String offset) {
		this.key = key;
		this.clcontext = clcontext;
		this.context = context;
		this.fudn = fudn;
		this.operuse = operuse;
		this.fudname = fudname;
		this.fudmin = fudmin;
		this.fudmax = fudmax;
		this.typchars = typchars;
		this.fudjustify = fudjustify;
		this.natostat = natostat;
		this.nmoddate = nmoddate;
		this.auditdate = auditdate;
		this.clname = clname;
		this.title = title;
		this.template = template;
		this.templateLength = templateLength;
		this.dataType = dataType;
		this.mfslabel = mfslabel;
		this.freetextind = freetextind;
		this.fudclass = fudclass;
		this.fnclass = fnclass;
		this.bitsize = bitsize;
		this.sinc = sinc;
		this.qinc = qinc;
		this.offset = offset;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public Double getClcontext() {
		return this.clcontext;
	}

	public void setClcontext(Double clcontext) {
		this.clcontext = clcontext;
	}

	public Double getContext() {
		return this.context;
	}

	public void setContext(Double context) {
		this.context = context;
	}

	public String getFudn() {
		return this.fudn;
	}

	public void setFudn(String fudn) {
		this.fudn = fudn;
	}

	public String getOperuse() {
		return this.operuse;
	}

	public void setOperuse(String operuse) {
		this.operuse = operuse;
	}

	public String getFudname() {
		return this.fudname;
	}

	public void setFudname(String fudname) {
		this.fudname = fudname;
	}

	public String getFudmin() {
		return this.fudmin;
	}

	public void setFudmin(String fudmin) {
		this.fudmin = fudmin;
	}

	public String getFudmax() {
		return this.fudmax;
	}

	public void setFudmax(String fudmax) {
		this.fudmax = fudmax;
	}

	public String getTypchars() {
		return this.typchars;
	}

	public void setTypchars(String typchars) {
		this.typchars = typchars;
	}

	public String getFudjustify() {
		return this.fudjustify;
	}

	public void setFudjustify(String fudjustify) {
		this.fudjustify = fudjustify;
	}

	public String getNatostat() {
		return this.natostat;
	}

	public void setNatostat(String natostat) {
		this.natostat = natostat;
	}

	public Date getNmoddate() {
		return this.nmoddate;
	}

	public void setNmoddate(Date nmoddate) {
		this.nmoddate = nmoddate;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

	public String getClname() {
		return this.clname;
	}

	public void setClname(String clname) {
		this.clname = clname;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public String getTemplateLength() {
		return this.templateLength;
	}

	public void setTemplateLength(String templateLength) {
		this.templateLength = templateLength;
	}

	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	public String getMfslabel() {
		return this.mfslabel;
	}

	public void setMfslabel(String mfslabel) {
		this.mfslabel = mfslabel;
	}

	public String getFreetextind() {
		return this.freetextind;
	}

	public void setFreetextind(String freetextind) {
		this.freetextind = freetextind;
	}

	public String getFudclass() {
		return this.fudclass;
	}

	public void setFudclass(String fudclass) {
		this.fudclass = fudclass;
	}

	public String getFnclass() {
		return this.fnclass;
	}

	public void setFnclass(String fnclass) {
		this.fnclass = fnclass;
	}

	public String getBitsize() {
		return this.bitsize;
	}

	public void setBitsize(String bitsize) {
		this.bitsize = bitsize;
	}

	public String getSinc() {
		return this.sinc;
	}

	public void setSinc(String sinc) {
		this.sinc = sinc;
	}

	public String getQinc() {
		return this.qinc;
	}

	public void setQinc(String qinc) {
		this.qinc = qinc;
	}

	public String getOffset() {
		return this.offset;
	}

	public void setOffset(String offset) {
		this.offset = offset;
	}

}
