package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineClChar generated by hbm2java
 */
public class BaselineClChar implements java.io.Serializable {

	private double classid;
	private String alpha;
	private String num;
	private String blank;
	private String spec;
	private String wild;
	private String dp;
	private Date auditdate;

	public BaselineClChar() {
	}

	public BaselineClChar(double classid) {
		this.classid = classid;
	}

	public BaselineClChar(double classid, String alpha, String num,
			String blank, String spec, String wild, String dp, Date auditdate) {
		this.classid = classid;
		this.alpha = alpha;
		this.num = num;
		this.blank = blank;
		this.spec = spec;
		this.wild = wild;
		this.dp = dp;
		this.auditdate = auditdate;
	}

	public double getClassid() {
		return this.classid;
	}

	public void setClassid(double classid) {
		this.classid = classid;
	}

	public String getAlpha() {
		return this.alpha;
	}

	public void setAlpha(String alpha) {
		this.alpha = alpha;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getBlank() {
		return this.blank;
	}

	public void setBlank(String blank) {
		this.blank = blank;
	}

	public String getSpec() {
		return this.spec;
	}

	public void setSpec(String spec) {
		this.spec = spec;
	}

	public String getWild() {
		return this.wild;
	}

	public void setWild(String wild) {
		this.wild = wild;
	}

	public String getDp() {
		return this.dp;
	}

	public void setDp(String dp) {
		this.dp = dp;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

}
