package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineClabbrev generated by hbm2java
 */
public class BaselineClabbrev implements java.io.Serializable {

	private BaselineClabbrevId id;

	public BaselineClabbrev() {
	}

	public BaselineClabbrev(BaselineClabbrevId id) {
		this.id = id;
	}

	public BaselineClabbrevId getId() {
		return this.id;
	}

	public void setId(BaselineClabbrevId id) {
		this.id = id;
	}

}
