package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineSetfldord generated by hbm2java
 */
public class BaselineSetfldord implements java.io.Serializable {

	private double key;
	private Double context;
	private Double fldordno;
	private String fieldcond;
	private String fieldrep;
	private String fldcol;
	private Date auditdate;
	private String prefixedind;
	private String ambiguityind;
	private String columnWidth;
	private String fieldName;
	private String mfslabel;
	private Double defaultind;

	public BaselineSetfldord() {
	}

	public BaselineSetfldord(double key) {
		this.key = key;
	}

	public BaselineSetfldord(double key, Double context, Double fldordno,
			String fieldcond, String fieldrep, String fldcol, Date auditdate,
			String prefixedind, String ambiguityind, String columnWidth,
			String fieldName, String mfslabel, Double defaultind) {
		this.key = key;
		this.context = context;
		this.fldordno = fldordno;
		this.fieldcond = fieldcond;
		this.fieldrep = fieldrep;
		this.fldcol = fldcol;
		this.auditdate = auditdate;
		this.prefixedind = prefixedind;
		this.ambiguityind = ambiguityind;
		this.columnWidth = columnWidth;
		this.fieldName = fieldName;
		this.mfslabel = mfslabel;
		this.defaultind = defaultind;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public Double getContext() {
		return this.context;
	}

	public void setContext(Double context) {
		this.context = context;
	}

	public Double getFldordno() {
		return this.fldordno;
	}

	public void setFldordno(Double fldordno) {
		this.fldordno = fldordno;
	}

	public String getFieldcond() {
		return this.fieldcond;
	}

	public void setFieldcond(String fieldcond) {
		this.fieldcond = fieldcond;
	}

	public String getFieldrep() {
		return this.fieldrep;
	}

	public void setFieldrep(String fieldrep) {
		this.fieldrep = fieldrep;
	}

	public String getFldcol() {
		return this.fldcol;
	}

	public void setFldcol(String fldcol) {
		this.fldcol = fldcol;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

	public String getPrefixedind() {
		return this.prefixedind;
	}

	public void setPrefixedind(String prefixedind) {
		this.prefixedind = prefixedind;
	}

	public String getAmbiguityind() {
		return this.ambiguityind;
	}

	public void setAmbiguityind(String ambiguityind) {
		this.ambiguityind = ambiguityind;
	}

	public String getColumnWidth() {
		return this.columnWidth;
	}

	public void setColumnWidth(String columnWidth) {
		this.columnWidth = columnWidth;
	}

	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getMfslabel() {
		return this.mfslabel;
	}

	public void setMfslabel(String mfslabel) {
		this.mfslabel = mfslabel;
	}

	public Double getDefaultind() {
		return this.defaultind;
	}

	public void setDefaultind(Double defaultind) {
		this.defaultind = defaultind;
	}

}
