package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineClasssnex generated by hbm2java
 */
public class BaselineClasssnex implements java.io.Serializable {

	private double key;
	private Date auditdate;
	private String snexpr;

	public BaselineClasssnex() {
	}

	public BaselineClasssnex(double key) {
		this.key = key;
	}

	public BaselineClasssnex(double key, Date auditdate, String snexpr) {
		this.key = key;
		this.auditdate = auditdate;
		this.snexpr = snexpr;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

	public String getSnexpr() {
		return this.snexpr;
	}

	public void setSnexpr(String snexpr) {
		this.snexpr = snexpr;
	}

}
