package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineSetdef generated by hbm2java
 */
public class BaselineSetdef implements java.io.Serializable {

	private double key;
	private String operator;
	private String fldvalue;

	public BaselineSetdef() {
	}

	public BaselineSetdef(double key) {
		this.key = key;
	}

	public BaselineSetdef(double key, String operator, String fldvalue) {
		this.key = key;
		this.operator = operator;
		this.fldvalue = fldvalue;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getFldvalue() {
		return this.fldvalue;
	}

	public void setFldvalue(String fldvalue) {
		this.fldvalue = fldvalue;
	}

}
