package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineStoplist generated by hbm2java
 */
public class BaselineStoplist implements java.io.Serializable {

	private String stopword;

	public BaselineStoplist() {
	}

	public BaselineStoplist(String stopword) {
		this.stopword = stopword;
	}

	public String getStopword() {
		return this.stopword;
	}

	public void setStopword(String stopword) {
		this.stopword = stopword;
	}

}
