package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineMsgusage generated by hbm2java
 */
public class BaselineMsgusage implements java.io.Serializable {

	private BaselineMsgusageId id;

	public BaselineMsgusage() {
	}

	public BaselineMsgusage(BaselineMsgusageId id) {
		this.id = id;
	}

	public BaselineMsgusageId getId() {
		return this.id;
	}

	public void setId(BaselineMsgusageId id) {
		this.id = id;
	}

}
