package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineFudexp generated by hbm2java
 */
public class BaselineFudexp implements java.io.Serializable {

	private double key;
	private String class_;
	private Date auditdate;
	private String fudexp;

	public BaselineFudexp() {
	}

	public BaselineFudexp(double key) {
		this.key = key;
	}

	public BaselineFudexp(double key, String class_, Date auditdate,
			String fudexp) {
		this.key = key;
		this.class_ = class_;
		this.auditdate = auditdate;
		this.fudexp = fudexp;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

	public String getFudexp() {
		return this.fudexp;
	}

	public void setFudexp(String fudexp) {
		this.fudexp = fudexp;
	}

}
