package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineFormatter generated by hbm2java
 */
public class BaselineFormatter implements java.io.Serializable {

	private String username;
	private String irisdefPriv;

	public BaselineFormatter() {
	}

	public BaselineFormatter(String username) {
		this.username = username;
	}

	public BaselineFormatter(String username, String irisdefPriv) {
		this.username = username;
		this.irisdefPriv = irisdefPriv;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getIrisdefPriv() {
		return this.irisdefPriv;
	}

	public void setIrisdefPriv(String irisdefPriv) {
		this.irisdefPriv = irisdefPriv;
	}

}
