package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineClChar21 generated by hbm2java
 */
public class BaselineClChar21 implements java.io.Serializable {

	private BaselineClChar21Id id;

	public BaselineClChar21() {
	}

	public BaselineClChar21(BaselineClChar21Id id) {
		this.id = id;
	}

	public BaselineClChar21Id getId() {
		return this.id;
	}

	public void setId(BaselineClChar21Id id) {
		this.id = id;
	}

}
