package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineMsgusrId generated by hbm2java
 */
public class BaselineMsgusrId implements java.io.Serializable {

	private Double key;
	private Double context;
	private String username;
	private String responsible;
	private String address;
	private String postcode;

	public BaselineMsgusrId() {
	}

	public BaselineMsgusrId(Double key, Double context, String username,
			String responsible, String address, String postcode) {
		this.key = key;
		this.context = context;
		this.username = username;
		this.responsible = responsible;
		this.address = address;
		this.postcode = postcode;
	}

	public Double getKey() {
		return this.key;
	}

	public void setKey(Double key) {
		this.key = key;
	}

	public Double getContext() {
		return this.context;
	}

	public void setContext(Double context) {
		this.context = context;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getResponsible() {
		return this.responsible;
	}

	public void setResponsible(String responsible) {
		this.responsible = responsible;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BaselineMsgusrId))
			return false;
		BaselineMsgusrId castOther = (BaselineMsgusrId) other;

		return ((this.getKey() == castOther.getKey()) || (this.getKey() != null
				&& castOther.getKey() != null && this.getKey().equals(
				castOther.getKey())))
				&& ((this.getContext() == castOther.getContext()) || (this
						.getContext() != null
						&& castOther.getContext() != null && this.getContext()
						.equals(castOther.getContext())))
				&& ((this.getUsername() == castOther.getUsername()) || (this
						.getUsername() != null
						&& castOther.getUsername() != null && this
						.getUsername().equals(castOther.getUsername())))
				&& ((this.getResponsible() == castOther.getResponsible()) || (this
						.getResponsible() != null
						&& castOther.getResponsible() != null && this
						.getResponsible().equals(castOther.getResponsible())))
				&& ((this.getAddress() == castOther.getAddress()) || (this
						.getAddress() != null
						&& castOther.getAddress() != null && this.getAddress()
						.equals(castOther.getAddress())))
				&& ((this.getPostcode() == castOther.getPostcode()) || (this
						.getPostcode() != null
						&& castOther.getPostcode() != null && this
						.getPostcode().equals(castOther.getPostcode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKey() == null ? 0 : this.getKey().hashCode());
		result = 37 * result
				+ (getContext() == null ? 0 : this.getContext().hashCode());
		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37
				* result
				+ (getResponsible() == null ? 0 : this.getResponsible()
						.hashCode());
		result = 37 * result
				+ (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result
				+ (getPostcode() == null ? 0 : this.getPostcode().hashCode());
		return result;
	}

}
