package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineMsgnlcmntId generated by hbm2java
 */
public class BaselineMsgnlcmntId implements java.io.Serializable {

	private Double key;
	private Date auditdate;
	private String nlcomment;

	public BaselineMsgnlcmntId() {
	}

	public BaselineMsgnlcmntId(Double key, Date auditdate, String nlcomment) {
		this.key = key;
		this.auditdate = auditdate;
		this.nlcomment = nlcomment;
	}

	public Double getKey() {
		return this.key;
	}

	public void setKey(Double key) {
		this.key = key;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

	public String getNlcomment() {
		return this.nlcomment;
	}

	public void setNlcomment(String nlcomment) {
		this.nlcomment = nlcomment;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BaselineMsgnlcmntId))
			return false;
		BaselineMsgnlcmntId castOther = (BaselineMsgnlcmntId) other;

		return ((this.getKey() == castOther.getKey()) || (this.getKey() != null
				&& castOther.getKey() != null && this.getKey().equals(
				castOther.getKey())))
				&& ((this.getAuditdate() == castOther.getAuditdate()) || (this
						.getAuditdate() != null
						&& castOther.getAuditdate() != null && this
						.getAuditdate().equals(castOther.getAuditdate())))
				&& ((this.getNlcomment() == castOther.getNlcomment()) || (this
						.getNlcomment() != null
						&& castOther.getNlcomment() != null && this
						.getNlcomment().equals(castOther.getNlcomment())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKey() == null ? 0 : this.getKey().hashCode());
		result = 37 * result
				+ (getAuditdate() == null ? 0 : this.getAuditdate().hashCode());
		result = 37 * result
				+ (getNlcomment() == null ? 0 : this.getNlcomment().hashCode());
		return result;
	}

}
