package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineSetfield generated by hbm2java
 */
public class BaselineSetfield implements java.io.Serializable {

	private double key;
	private Double fudn;
	private Double context;
	private Double ordercode;
	private String altfldcont;
	private String fielddesc;
	private Date auditdate;
	private String fudjustify;
	private String altname;
	private String mfslabel;

	public BaselineSetfield() {
	}

	public BaselineSetfield(double key) {
		this.key = key;
	}

	public BaselineSetfield(double key, Double fudn, Double context,
			Double ordercode, String altfldcont, String fielddesc,
			Date auditdate, String fudjustify, String altname, String mfslabel) {
		this.key = key;
		this.fudn = fudn;
		this.context = context;
		this.ordercode = ordercode;
		this.altfldcont = altfldcont;
		this.fielddesc = fielddesc;
		this.auditdate = auditdate;
		this.fudjustify = fudjustify;
		this.altname = altname;
		this.mfslabel = mfslabel;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public Double getFudn() {
		return this.fudn;
	}

	public void setFudn(Double fudn) {
		this.fudn = fudn;
	}

	public Double getContext() {
		return this.context;
	}

	public void setContext(Double context) {
		this.context = context;
	}

	public Double getOrdercode() {
		return this.ordercode;
	}

	public void setOrdercode(Double ordercode) {
		this.ordercode = ordercode;
	}

	public String getAltfldcont() {
		return this.altfldcont;
	}

	public void setAltfldcont(String altfldcont) {
		this.altfldcont = altfldcont;
	}

	public String getFielddesc() {
		return this.fielddesc;
	}

	public void setFielddesc(String fielddesc) {
		this.fielddesc = fielddesc;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

	public String getFudjustify() {
		return this.fudjustify;
	}

	public void setFudjustify(String fudjustify) {
		this.fudjustify = fudjustify;
	}

	public String getAltname() {
		return this.altname;
	}

	public void setAltname(String altname) {
		this.altname = altname;
	}

	public String getMfslabel() {
		return this.mfslabel;
	}

	public void setMfslabel(String mfslabel) {
		this.mfslabel = mfslabel;
	}

}
