package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineMsgFuncId generated by hbm2java
 */
public class BaselineMsgFuncId implements java.io.Serializable {

	private double mtfid;
	private double funcid;

	public BaselineMsgFuncId() {
	}

	public BaselineMsgFuncId(double mtfid, double funcid) {
		this.mtfid = mtfid;
		this.funcid = funcid;
	}

	public double getMtfid() {
		return this.mtfid;
	}

	public void setMtfid(double mtfid) {
		this.mtfid = mtfid;
	}

	public double getFuncid() {
		return this.funcid;
	}

	public void setFuncid(double funcid) {
		this.funcid = funcid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BaselineMsgFuncId))
			return false;
		BaselineMsgFuncId castOther = (BaselineMsgFuncId) other;

		return (this.getMtfid() == castOther.getMtfid())
				&& (this.getFuncid() == castOther.getFuncid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMtfid();
		result = 37 * result + (int) this.getFuncid();
		return result;
	}

}
