package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineMsgflog generated by hbm2java
 */
public class BaselineMsgflog implements java.io.Serializable {

	private BaselineMsgflogId id;

	public BaselineMsgflog() {
	}

	public BaselineMsgflog(BaselineMsgflogId id) {
		this.id = id;
	}

	public BaselineMsgflogId getId() {
		return this.id;
	}

	public void setId(BaselineMsgflogId id) {
		this.id = id;
	}

}
