package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineAbrtypeId generated by hbm2java
 */
public class BaselineAbrtypeId implements java.io.Serializable {

	private String abrtype;
	private String typedesc;

	public BaselineAbrtypeId() {
	}

	public BaselineAbrtypeId(String abrtype, String typedesc) {
		this.abrtype = abrtype;
		this.typedesc = typedesc;
	}

	public String getAbrtype() {
		return this.abrtype;
	}

	public void setAbrtype(String abrtype) {
		this.abrtype = abrtype;
	}

	public String getTypedesc() {
		return this.typedesc;
	}

	public void setTypedesc(String typedesc) {
		this.typedesc = typedesc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BaselineAbrtypeId))
			return false;
		BaselineAbrtypeId castOther = (BaselineAbrtypeId) other;

		return ((this.getAbrtype() == castOther.getAbrtype()) || (this
				.getAbrtype() != null
				&& castOther.getAbrtype() != null && this.getAbrtype().equals(
				castOther.getAbrtype())))
				&& ((this.getTypedesc() == castOther.getTypedesc()) || (this
						.getTypedesc() != null
						&& castOther.getTypedesc() != null && this
						.getTypedesc().equals(castOther.getTypedesc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAbrtype() == null ? 0 : this.getAbrtype().hashCode());
		result = 37 * result
				+ (getTypedesc() == null ? 0 : this.getTypedesc().hashCode());
		return result;
	}

}
