package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineSetflog generated by hbm2java
 */
public class BaselineSetflog implements java.io.Serializable {

	private BaselineSetflogId id;

	public BaselineSetflog() {
	}

	public BaselineSetflog(BaselineSetflogId id) {
		this.id = id;
	}

	public BaselineSetflogId getId() {
		return this.id;
	}

	public void setId(BaselineSetflogId id) {
		this.id = id;
	}

}
