package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineMsgTemp generated by hbm2java
 */
public class BaselineMsgTemp implements java.io.Serializable {

	private String delIrn;

	public BaselineMsgTemp() {
	}

	public BaselineMsgTemp(String delIrn) {
		this.delIrn = delIrn;
	}

	public String getDelIrn() {
		return this.delIrn;
	}

	public void setDelIrn(String delIrn) {
		this.delIrn = delIrn;
	}

}
