package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineFfirnbasic generated by hbm2java
 */
public class BaselineFfirnbasic implements java.io.Serializable {

	private double key;
	private Double context;
	private String ffirn;
	private String natostat;
	private Date nmoddate;
	private String ffclass;
	private Date revdate;
	private Date auditdate;
	private String ffirnname;
	private String typchars;
	private String ffirnmin;
	private String ffirnmax;
	private String origffcl;
	private String origffirn;
	private Date origdate;
	private String clname;

	public BaselineFfirnbasic() {
	}

	public BaselineFfirnbasic(double key) {
		this.key = key;
	}

	public BaselineFfirnbasic(double key, Double context, String ffirn,
			String natostat, Date nmoddate, String ffclass, Date revdate,
			Date auditdate, String ffirnname, String typchars, String ffirnmin,
			String ffirnmax, String origffcl, String origffirn, Date origdate,
			String clname) {
		this.key = key;
		this.context = context;
		this.ffirn = ffirn;
		this.natostat = natostat;
		this.nmoddate = nmoddate;
		this.ffclass = ffclass;
		this.revdate = revdate;
		this.auditdate = auditdate;
		this.ffirnname = ffirnname;
		this.typchars = typchars;
		this.ffirnmin = ffirnmin;
		this.ffirnmax = ffirnmax;
		this.origffcl = origffcl;
		this.origffirn = origffirn;
		this.origdate = origdate;
		this.clname = clname;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public Double getContext() {
		return this.context;
	}

	public void setContext(Double context) {
		this.context = context;
	}

	public String getFfirn() {
		return this.ffirn;
	}

	public void setFfirn(String ffirn) {
		this.ffirn = ffirn;
	}

	public String getNatostat() {
		return this.natostat;
	}

	public void setNatostat(String natostat) {
		this.natostat = natostat;
	}

	public Date getNmoddate() {
		return this.nmoddate;
	}

	public void setNmoddate(Date nmoddate) {
		this.nmoddate = nmoddate;
	}

	public String getFfclass() {
		return this.ffclass;
	}

	public void setFfclass(String ffclass) {
		this.ffclass = ffclass;
	}

	public Date getRevdate() {
		return this.revdate;
	}

	public void setRevdate(Date revdate) {
		this.revdate = revdate;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

	public String getFfirnname() {
		return this.ffirnname;
	}

	public void setFfirnname(String ffirnname) {
		this.ffirnname = ffirnname;
	}

	public String getTypchars() {
		return this.typchars;
	}

	public void setTypchars(String typchars) {
		this.typchars = typchars;
	}

	public String getFfirnmin() {
		return this.ffirnmin;
	}

	public void setFfirnmin(String ffirnmin) {
		this.ffirnmin = ffirnmin;
	}

	public String getFfirnmax() {
		return this.ffirnmax;
	}

	public void setFfirnmax(String ffirnmax) {
		this.ffirnmax = ffirnmax;
	}

	public String getOrigffcl() {
		return this.origffcl;
	}

	public void setOrigffcl(String origffcl) {
		this.origffcl = origffcl;
	}

	public String getOrigffirn() {
		return this.origffirn;
	}

	public void setOrigffirn(String origffirn) {
		this.origffirn = origffirn;
	}

	public Date getOrigdate() {
		return this.origdate;
	}

	public void setOrigdate(Date origdate) {
		this.origdate = origdate;
	}

	public String getClname() {
		return this.clname;
	}

	public void setClname(String clname) {
		this.clname = clname;
	}

}
