package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineFfirnflog generated by hbm2java
 */
public class BaselineFfirnflog implements java.io.Serializable {

	private BaselineFfirnflogId id;

	public BaselineFfirnflog() {
	}

	public BaselineFfirnflog(BaselineFfirnflogId id) {
		this.id = id;
	}

	public BaselineFfirnflogId getId() {
		return this.id;
	}

	public void setId(BaselineFfirnflogId id) {
		this.id = id;
	}

}
