package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineFfirnchain generated by hbm2java
 */
public class BaselineFfirnchain implements java.io.Serializable {

	private double key;
	private Double fudnref;
	private Double context;
	private String ffordno;
	private Date auditdate;
	private String chksumind;
	private String structlabel;

	public BaselineFfirnchain() {
	}

	public BaselineFfirnchain(double key) {
		this.key = key;
	}

	public BaselineFfirnchain(double key, Double fudnref, Double context,
			String ffordno, Date auditdate, String chksumind, String structlabel) {
		this.key = key;
		this.fudnref = fudnref;
		this.context = context;
		this.ffordno = ffordno;
		this.auditdate = auditdate;
		this.chksumind = chksumind;
		this.structlabel = structlabel;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public Double getFudnref() {
		return this.fudnref;
	}

	public void setFudnref(Double fudnref) {
		this.fudnref = fudnref;
	}

	public Double getContext() {
		return this.context;
	}

	public void setContext(Double context) {
		this.context = context;
	}

	public String getFfordno() {
		return this.ffordno;
	}

	public void setFfordno(String ffordno) {
		this.ffordno = ffordno;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

	public String getChksumind() {
		return this.chksumind;
	}

	public void setChksumind(String chksumind) {
		this.chksumind = chksumind;
	}

	public String getStructlabel() {
		return this.structlabel;
	}

	public void setStructlabel(String structlabel) {
		this.structlabel = structlabel;
	}

}
