package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineMessErr generated by hbm2java
 */
public class BaselineMessErr implements java.io.Serializable {

	private String str;

	public BaselineMessErr() {
	}

	public BaselineMessErr(String str) {
		this.str = str;
	}

	public String getStr() {
		return this.str;
	}

	public void setStr(String str) {
		this.str = str;
	}

}
