package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineSetsnex generated by hbm2java
 */
public class BaselineSetsnex implements java.io.Serializable {

	private double key;
	private Date auditdate;
	private String setsnexpr;

	public BaselineSetsnex() {
	}

	public BaselineSetsnex(double key) {
		this.key = key;
	}

	public BaselineSetsnex(double key, Date auditdate, String setsnexpr) {
		this.key = key;
		this.auditdate = auditdate;
		this.setsnexpr = setsnexpr;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

	public String getSetsnexpr() {
		return this.setsnexpr;
	}

	public void setSetsnexpr(String setsnexpr) {
		this.setsnexpr = setsnexpr;
	}

}
