package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BaselineMsgsnex generated by hbm2java
 */
public class BaselineMsgsnex implements java.io.Serializable {

	private double key;
	private Date auditdate;
	private String msgsnexpr;

	public BaselineMsgsnex() {
	}

	public BaselineMsgsnex(double key) {
		this.key = key;
	}

	public BaselineMsgsnex(double key, Date auditdate, String msgsnexpr) {
		this.key = key;
		this.auditdate = auditdate;
		this.msgsnexpr = msgsnexpr;
	}

	public double getKey() {
		return this.key;
	}

	public void setKey(double key) {
		this.key = key;
	}

	public Date getAuditdate() {
		return this.auditdate;
	}

	public void setAuditdate(Date auditdate) {
		this.auditdate = auditdate;
	}

	public String getMsgsnexpr() {
		return this.msgsnexpr;
	}

	public void setMsgsnexpr(String msgsnexpr) {
		this.msgsnexpr = msgsnexpr;
	}

}
