package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineAbrtype generated by hbm2java
 */
public class BaselineAbrtype implements java.io.Serializable {

	private BaselineAbrtypeId id;

	public BaselineAbrtype() {
	}

	public BaselineAbrtype(BaselineAbrtypeId id) {
		this.id = id;
	}

	public BaselineAbrtypeId getId() {
		return this.id;
	}

	public void setId(BaselineAbrtypeId id) {
		this.id = id;
	}

}
