package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineClassdef generated by hbm2java
 */
public class BaselineClassdef implements java.io.Serializable {

	private BaselineClassdefId id;
	private String operator;
	private String fldvalue;

	public BaselineClassdef() {
	}

	public BaselineClassdef(BaselineClassdefId id) {
		this.id = id;
	}

	public BaselineClassdef(BaselineClassdefId id, String operator,
			String fldvalue) {
		this.id = id;
		this.operator = operator;
		this.fldvalue = fldvalue;
	}

	public BaselineClassdefId getId() {
		return this.id;
	}

	public void setId(BaselineClassdefId id) {
		this.id = id;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getFldvalue() {
		return this.fldvalue;
	}

	public void setFldvalue(String fldvalue) {
		this.fldvalue = fldvalue;
	}

}
