package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineMsgusr generated by hbm2java
 */
public class BaselineMsgusr implements java.io.Serializable {

	private BaselineMsgusrId id;

	public BaselineMsgusr() {
	}

	public BaselineMsgusr(BaselineMsgusrId id) {
		this.id = id;
	}

	public BaselineMsgusrId getId() {
		return this.id;
	}

	public void setId(BaselineMsgusrId id) {
		this.id = id;
	}

}
