package org.miliconvert.adatp3.hibernate;

// Generated 3 sept. 2009 09:13:44 by Hibernate Tools 3.2.4.GA

/**
 * BaselineClassdefId generated by hbm2java
 */
public class BaselineClassdefId implements java.io.Serializable {

	private double context;
	private double setfield;

	public BaselineClassdefId() {
	}

	public BaselineClassdefId(double context, double setfield) {
		this.context = context;
		this.setfield = setfield;
	}

	public double getContext() {
		return this.context;
	}

	public void setContext(double context) {
		this.context = context;
	}

	public double getSetfield() {
		return this.setfield;
	}

	public void setSetfield(double setfield) {
		this.setfield = setfield;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BaselineClassdefId))
			return false;
		BaselineClassdefId castOther = (BaselineClassdefId) other;

		return (this.getContext() == castOther.getContext())
				&& (this.getSetfield() == castOther.getSetfield());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getContext();
		result = 37 * result + (int) this.getSetfield();
		return result;
	}

}
